remote_theme: 256-Foundation/midnight-theme
title: GRANTS256
description: Free Open-Source Bitcoin Mining Development Grants
github:
  repository_url: https://256foundation.org
  owner_url: https://256foundation.org
